name: groovy-gorillas
base: core18
version: '1.0'
summary: Groovy Gorillas
description: |
  Groovy Gorillas: a tweak of Al Sweigart's Pygame port of the venerable GORILLAS.BAS,
  but with the gorillas made to be Groovy in honour of Ubuntu 20.10 Groovy Gorilla!
  Also, now there is sound.

grade: stable
confinement: strict

parts:
  groovy-gorillas:
    plugin: dump
    source: https://github.com/stuartlangridge/groovy-gorillas.git
    stage-packages:
      - python-pygame
      - libslang2
      - libglu1-mesa
      - freeglut3
      #- libpulse0
  assets:
    plugin: dump
    source: snap/local

apps:
  groovy-gorillas:
    command: python2.7 $SNAP/groovy-gorillas.py
    #environment:
    #  LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH
    plugs: 
      - x11
      #- audio-playback
